### ISSUE TITLE
ipfs.pics seems to have no ipfs server running, images are not loading

### ISSUE THREAD

**Issue by GwenNelson** [ipfspics/server#49] opened 2016-10-24 21:49 UTC
At least this isn't loading along with many other images i've uploaded in the past:

https://ipfs.pics/ipfs/QmTbifDGSNx5Gu1XjbWTa8G1JR5m1PTc63cnU5FT9JzWvU

Unable to load the same image directly from IPFS either:
gareth@skynet:~/Downloads/go-ipfs$ ipfs cat /ipfs/QmTbifDGSNx5Gu1XjbWTa8G1JR5m1PTc63cnU5FT9JzWvU
Error: merkledag: not found

**Comment by dylanaraps** [comment] 2016-11-01 05:09
I'm having the same issue. :(

**Comment by cloutier** [comment] 2016-11-13 16:37
Working on this, server will be down for a few hours while I upgrade to a bigger machine

**Comment by xloem** [comment] 2016-12-24 21:24
@cloutier it seems the situation has worsened -- can I run a mirror?

**Comment by cloutier** [comment] 2016-12-25 15:50
Of course! Instructions are here: https://github.com/ipfspics/ipfspics-server/wiki/How-to-install-ipfs.pics-on-LAMP-(recommended)

I have way to much on my plates with school and work in the next few months, and ipfs.pics has become unmanageable for me. I would much prefer that people run mirrors and that I make ipfs.pics redirect to the best community ones, so that everything is not centralized on me.

**Comment by xloem** [comment] 2016-12-25 22:46
Great!  I'll figure it out and set something up.  Could you share your stored images on ipfs, or in any other way, so that we can bring them back to life?

**Comment by xloem** [comment] 2016-12-26 01:48
http://66.172.27.106/

**Comment by cloutier** [comment] 2016-12-28 23:45
I have a bit of free credit on Azure and I will be using it to seed on ipfs all the pictures that were uploaded over the next year. I also have a backup of the database that I can upload when I get home.

**Comment by cloutier** [comment] 2016-12-28 23:49
I'm thinking I could add all the IPs of the volonteers who want to run an instance to the ipfs.pics DNS to make things more distributed. Do you want to participate @xloem?

**Comment by xloem** [comment] 2016-12-29 11:04
@cloutier that would be great!  Thank you so much for helping this website come back to life.

**Comment by cloutier** [comment] 2016-12-29 19:00
@xloem I added a dump of the db, without the banned content (as to not promote it by accident). I'll start my seed node early next year, but a lot of the content is already propagated and should load.

**Comment by xloem** [comment] 2016-12-29 20:49
I've applied it!  They're all back!  What do you think of putting my ip into something like xloem.ipfs.pics?  Then I could get an SSL cert for it..

**Comment by jbenet** [comment] 2016-12-29 20:57
Thanks for making ipfs.pics awesome @cloutier -- how can we help here? bandwidth? management? (we can throw $$ towards bandwidth, and now that we have js-ipfs we could see about updating ipfs.pics with js-ipfs to retrieve directly from the network and save you bandwidth.

cc @lgierth @daviddias

**Comment by jbenet** [comment] 2016-12-29 20:58
@victorbjelkholm suggests this would be a great way to try out https://github.com/ipfs/ipfs-cluster too, cc @hsanjuan

**Comment by cloutier** [comment] 2016-12-30 16:25
First of all thank you for all the kind words! I was fed up with ipfs.pics not working and not having time to fix it. After closing it I realized how many people like it and used it. I have been thinking over the last days and I think that I should continue to pursue the development. I used free credits I had on AWS to redeploy https://ipfs.pics/ and I created http://xloem.ipfs.pics/ for @xloem.

My end goal would be to turn ipfs.pics into a profitable free software corporation like [Automaticc](https://automattic.com/). I know photo sharing is a very low margin industry, but I still hope it could support me and maybe the development of ipfs itself. Knowing this I would feel bad taking money from the ipfs project, but I would gladly accept if you have contacts for more credits on any cloud. 

So here is my plan for 2017 to fix everything that was annoying me and make ipfs.pics huge:
- I took the promise of the permanent web very seriously and I was storing everything. My plan was to move content with little views to a cheap raspberry pi in a basement. This plan is not off the table but I don’t think anymore that it is sustainable, could still be an interesting way to try out ipfs-cluster indeed though. I think I should make ipfs.pics easier to install, let other keep the content I don’t find relevant and no longer store everything. Plus there is no point of having a distributed system if there is only one main instance.
- A big refactoring of the code. I improved a lot and I see a lot of wrong things. I think @jbenet’s suggestion to use js-ipfs is something much needed too. I want to use composer more and to use a templating engine. I also want the code to be as easy as possible to get into as a newcomer. 
- A better community. I want to thank those who contribute and give them a subdomain if they want to. I will put banners on the site to recruit contributors too - and please tell me @xloem if you want to become a core contributor and have issues assigned to you. I want to also fix the discrepancy #2 that ipfs.pics doesn’t exactly follow the ipfs standard. I want to create a roadmap too and any help/advice on how to lead a large open source project would be appreciated!
- A better monetization plan. Google Adsense is not getting much revenue and doesn’t feel right either. I am thinking about making a decentralized comments system using an Ethereum contract with a price of 1$ per comment. I’m open to other ideas!

ipfs.pics is back online, so I’m closing this issue, but we can continue the discussion here.

**Closed as completed by cloutier** 2016-12-30 16:25 UTC

**Comment by xloem** [comment] 2016-12-30 18:05
@cloutier this is incredible news!  However there is still no ipfs daemon running on your new server; the issue is not quite resolved.

**Comment by cloutier** [comment] 2016-12-30 18:40
I was running ipfs without the automatic restart on crashes, it's fixed now.

**Comment by xloem** [comment] 2017-01-01 15:01
Nice!  Looking forward to the old ipfs store resurrecting.  I have a script running on my host attempting to pin all the hashes in the db as soon as they are available on ipfs.

I came here from https://www.steemit.com/ .  Steemit is a blockchain social media platform; a lot of the posters used ipfs.pics for their images, so these urls are now stored "permanently" in steem's blockchain.  When the main site went down, these images seemed to disappear and people probably lost trust in ipfs as an image host.  Instead they returned to using much worst hosts that don't have any distributed storage or hash verification and are actually less future-proof, if more reliable this past year.

I thought if I could get ipfs.pics back, I might make a post about it on steemit.  When people upvote a post it gains steem dollars, which I hoped I could use to offset the cost of the server.  But now I present this idea to you!

**Comment by seeARMS** [comment] 2017-07-05 00:24
This seems to be down again - has there been any updates to the status of this project?

On another note, I've been considering creating a (similar) distributed image-hosting service, but storing all images on the blockchain across all participants. Essentially Filecoin except for publicly-accessible images. This should avoid the centralization issues @xloem is referring to with the main site going down.

**Comment by ghost** [comment] 2017-07-05 00:30
@xloem it'd be better to store actual ipfs links, not http links. Good example of the advantage of content-addressing over location-addressing :)
